- hosts: frontends
  gather_facts: false
  tasks:
  - name: Curl website
    uri:
      url: "http://{{ item }}"
      return_content: yes
      status_code: 200
    # Checking in the dynamic inventory
    with_items:
      - "{{ inventory_hostname}}"
    register: webpage
        
  - debug: var=webpage.results[0].content

  - name: Fail if 'Ansible has done its job' is not in the page content
    fail:
    when: "'Ansible has done its job' not in webpage.results[0].content"

