---
- name: Download Private key
  get_url:
    url: http://www.opentlc.com/download/ansible_bootcamp/openstack_keys/openstack.pem
    dest: "/tmp"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: 0400

- name: Download Public key
  get_url:
    url: http://www.opentlc.com/download/ansible_bootcamp/openstack_keys/openstack.pub
    dest: "/tmp"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: 0400

- name: Create OSP keypair 2nd key_pair
  os_keypair:
    cloud: openstack
    state: present
    name: second_key_pair
    public_key_file: "/tmp/openstack.pub"


